/** 모달 리듀서 */
export { default as PaperDetailAprvInfoReducer } from '../popup/PaperDetailAprvSlice'
export { default as SuccessionInfoReducer } from '../popup/SuccessionSlice'
export { default as SetlCardAprvInfoReducer } from '../popup/SetlCardAprvSlice'
export { default as SetledAprvInfoReducer } from '../popup/SetledAprvInfoSlice'
export { default as VhclSpecHstryReducer } from '../popup/VhclSpecHstrySlice'
export { default as VhclTransHstryReducer } from '../popup/VhclTransHstrySlice'
export { default as LocgovInfoReducer } from '../popup/LocgovInfoSlice'
export { default as CarInfoReducer } from '../popup/CarInfoSlice'
export { default as RfIdHistoryReducer } from '../popup/RfIdHistorySlice'
export { default as MainIllegalityReducer } from '../popup/MainPageIllegalitySlice'
export { default as SurveyReducer } from '../popup/SurveySlice'
export { default as VhclBzmnPrmsnReducer } from '../popup/VhclBzmnPrmsnSlice'
export { default as NoticeInfoReducer } from '../popup/NoticeSlice'
export { default as OilStationInfoReducer } from '../popup/OilStationSlice'
export { default as DecisionBypeReducer } from '../popup/DecisionBypeSlice'
export { default as LgovTrfntfReducer } from '../popup/LgovTrfntfSlice'
export { default as ExamResultReducer } from '../popup/ExamResultSlice'
export { default as ExaathrReducer } from '../popup/ExaathrSlice'
export { default as BfdnDspsReducer } from '../popup/BfdnDspsSlice'
export { default as AdmdspNotieReducer } from '../popup/AdmdspNotieSlice'
export { default as IlgIsdReducer } from '../popup/IlgIsdSlice'
export { default as RrnoDecReducer } from '../popup/ShowRrnoSlice'
export { default as StdTnkReducer } from '../popup/StdTnkCpctySlice'

/** 페이지 리듀서 */
export { default as LpavReducer } from '../page/LpavSlice'
export { default as IsdReducer } from '../page/IsdSlice'
export { default as ShlReducer } from '../page/ShlSlice'
export { default as DmalReducer } from '../page/DmalSlice'
export { default as TcelReducer } from '../page/TcelSlice'
export { default as TaavelReducer } from '../page/TaavelSlice'
export { default as DvhalReducer } from '../page/DvhalSlice'
export { default as NblReducer } from '../page/NblSlice'
export { default as DdalReducer } from '../page/DdalSlice'
export { default as StnTabsReducer } from '../page/StnTabsSlice'

/** 검색 리듀서 */
export { default as SeacrhReducer } from '../search/SearchSlice'
